[package]
name = "mathcraft-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "mathcraft_rs"
path = "src/lib.rs"

[[bin]]
name = "mathcraft-rs"
path = "src/main.rs"


[dependencies]
rust_decimal = "1.36.0"
rust_decimal_macros = "1.36.0"
